### PR TITLE
Re-write inputs form using React and make input parsing/validation asynchronous

### LINKED ISSUE #179: Error pages on some Tax-Brain submissions
Some users have reported receiving errors when submitting their inputs on Tax-Brain. This is because their inputs are not being validated and returned by the compute cluster before the request times out. Thus, the page hangs and eventually an error page is shown. 

To resolve this, I am going to bump the timeout time on requests from 2.5 seconds to 4 seconds. I am also going to make the process of validating user inputs asynchronous. 

This will be similar to the process for actually running the simulation: user submits inputs, a dialog notifies them that the inputs have been submitted and are being validated, and either the simulation will be kicked off or the errors will be shown to the user.

### PR DESCRIPTION
**Pull request by hdoupe**
This PR resolves #179 and partially #81 by making the loading of the inputs form and the submission of the user's inputs asynchronous:

load-page

async-submit

To do this, the inputs form was re-written with ReactJS. I explored using ajax to submit the form as it is now, but error handling made this approach awkward. Further, re-writing the form in javascript will allow COMP to have a more responsive and creative inputs page by allowing for stuff like asynchronous form submissions and making it easy to write custom user inputs. 

The inputs validation step was also made asynchronous. This was done because it was difficult to enforce a low request timeout time on the validation step. Further, some models may have more complex validation processes that take much longer than is reasonable to wait for a server to respond to a request.   

TODO:
- [x] Render all inputs asynchronously.
- [x] User inputs validation is asynchronous.
- [x] Submit user inputs on successful validation.
- [x] Display errors on unsuccessful validation.
- [x] Improve speed of page. On large inputs pages, there is a bit of a lag on key strokes.
- [x] Add missing UI elements:
  - [x] Check box field
  - [x] Inputs box changes color when the value is different than the default
  - [x] Default shown under input box when value is different than the default
  - [x] Dropdown fields for parameters with choice validator
  - [x] Support wildcard/reverse operator syntax
- [x] Edit parameters page.
- [x] "Are you sure you want to submit..." dialog box
  - [x] Confirm user wants to run
  - [x] Display price on run button (unless sponsored)
  - [x] Dialog box checks if user is authenticated and redirects to login if so.
  - [x] Dialog box checks if user has pmt (unless model is sponsored) and redirects to payment page.
- [x] Remove all of the no longer used Django form creation code (!)
- [x] Testing, testing, testing

### CODE REVIEW

**Comment by hdoupe** [comment]
This PR also makes it possible to do live validation on user inputs:

quick-validation

**Comment by hdoupe** [comment]
RE lag on keystrokes: It looks like the entire form is re-rendering on each key-stroke. It ought to be much faster once I change it to only re-render the field that was updated.

**Comment by hdoupe** [comment]
The latest commits fix the key-stroke lag issue. Now, the inputs are just as responsive as regular html input boxes. I wrapped the nested components (MetaParameters and MajorSection->Section1->Section2->Param) with [react.memo](https://reactjs.org/docs/react-api.html#reactmemo) and defined an `areEqual` function to check whether the component's values had changed and thus the component needed to be re-rendered. The result is only the components that must be re-rendered are re-rendered.

**Comment by hdoupe** [comment]
PR #185 is almost ready to go. I am trying to resolve an issue with the `select` inputs because `react-select` doesn't allow one to put the same input value twice by default. However, all other input features are functioning correctly. I'm going to spend some time testing the site and building in some redundancy measures to make sure that jobs aren't lost if one of the API endpoints misses a request.

**Comment by hdoupe** [comment]
This PR is live at [dev.compmodels.org](https://dev.compmodels.org)

**Comment by MattHJensen** [comment]
First pass: 

- [ ] information i hover over not working
- [ ] nav link to "behavior" and "policy" not working
- [ ] can't add multiple values from boolean dropdown:
image

**Comment by hdoupe** [comment]
Thanks for the feedback. I just pushed the fix for the sidebar. The info boxes are working for me in firefox and chrome? They are light grey instead of black for some reason. 

I'm working on the can't add the multiple of the same issue right now. For some reason, that's the default behavior of `react-select`, and I'm having trouble turning it off.

**Comment by MattHJensen** [comment]
> The info boxes are working for me in firefox and chrome? They are light grey instead of black for some reason.

I'm on up-to-date Chrome.

**Comment by hdoupe** [comment]
Ok, I just uninstalled and reinstalled chrome, and the tooltips work. I may need to use `react-bootstrap`'s [version of tooltips](https://react-bootstrap.github.io/components/overlays/) to get it to work more reliably though. I'll give that a shot and let you know when I've pushed it.

**Comment by hdoupe** [comment]
I'm going to merge #185. There are a few things that need to be touched up on and documented, but I'm excited to get the new page in front of users.

**Pull request merged**
